---
- name: Stop EC2 instances
  hosts: all
  become: true
  become_method: sudo
  ignore_errors: false
  tasks:
  - name: Gather facts
    action: ec2_facts

  - name: Stop myserver instance
    local_action:
        module: ec2
        region: "all"
        instance_ids: "{{all}}"
        state: stopped
