---
- name: Wordpress
  hosts: 34.214.130.87
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: Install prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
      tags: [ system ]

    - name: Install LAMP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]
      tags: [ system ]

    - name: Install PHP Extensions
      apt: name={{ item }} update_cache=yes state=latest
      loop: "{{ php_modules }}"
      tags: [ system ]

  # Apache Configuration
    - name: Create document root
      file:
        path: "/var/www/{{ safa-g.com }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'
      tags: [ apache ]

    - name: Set up Apache VirtualHost
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache
      tags: [ apache ]

    - name: Enable rewrite module
      shell: /usr/sbin/a2enmod rewrite
      notify: Reload Apache
      tags: [ apache ]

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache
      tags: [ apache ]

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      notify: Restart Apache
      tags: [ apache ]

  # MySQL Configuration
    - name: Set the root password
      mysql_user:
        name: root
        password: "{{ 52Z86P@&$64vFkPG6Z674yAA8 }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
      tags: [ mysql, mysql-root ]

    - name: Remove all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "{{ 52Z86P@&$64vFkPG6Z674yAA8 }}"
      tags: [ mysql ]

    - name: Remove the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ 52Z86P@&$64vFkPG6Z674yAA8 }}"
      tags: [ mysql ]

    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ 52Z86P@&$64vFkPG6Z674yAA8 }}"
      tags: [ mysql ]

    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{ Bob }}"
        password: "{{ 52Z86P@&$64vFkPG6Z674yAA8 }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ 52Z86P@&$64vFkPG6Z674yAA8 }}"
      tags: [ mysql ]

      - name: Create MySQL user for WordPress
        mysql_user:
          name: "{{ Ben }}"
          password: "{{ 52Z86P@&$64vFkPG6Z674yAA8 }}"
          priv: "{{ mysql_db }}.*:ALL"
          state: present
          login_user: root
          login_password: "{{ 52Z86P@&$64vFkPG6Z674yAA8 }}"
        tags: [ mysql ]

      - name: Create MySQL user for WordPress
        mysql_user:
          name: "{{ Lisa }}"
          password: "{{ 52Z86P@&$64vFkPG6Z674yAA8 }}"
          priv: "{{ mysql_db }}.*:ALL"
          state: present
          login_user: root
          login_password: "{{ 52Z86P@&$64vFkPG6Z674yAA8 }}"
        tags: [ mysql ]

      - name: Create MySQL user for WordPress
        mysql_user:
          name: "{{ Katty }}"
          password: "{{ 52Z86P@&$64vFkPG6Z674yAA8 }}"
          priv: "{{ mysql_db }}.*:ALL"
          state: present
          login_user: root
          login_password: "{{ 52Z86P@&$64vFkPG6Z674yAA8 }}"
        tags: [ mysql ]

  # UFW Configuration
    - name: "UFW - Allow HTTP on port {{ 80 }}"
      ufw:
        rule: allow
        port: "{{ 80 }}"
        proto: tcp
      tags: [ system ]

  # WordPress Configuration
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ safa-g.com }}"
        remote_src: yes
        creates: "/var/www/{{ safa-g.com }}/wordpress"
      tags: [ wordpress ]

    - name: Set ownership
      file:
        path: "/var/www/{{ safa-g.com }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      tags: [ wordpress ]

    - name: Set permissions for directories
      shell: "/usr/bin/find /var/www/{{ safa-g.com }}/wordpress/ -type d -exec chmod 750 {} \\;"
      tags: [ wordpress ]

    - name: Set permissions for files
      shell: "/usr/bin/find /var/www/{{ safa-g.com }}/wordpress/ -type f -exec chmod 640 {} \\;"
      tags: [ wordpress ]

    - name: Set up wp-config
      template:
        src: "files/wp-config.php.j2"
        dest: "/var/www/{{ safa-g.com }}/wordpress/wp-config.php"
      tags: [ wordpress ]

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted